/**
 * Slack emoji shortcode to Unicode conversion utility.
 * Converts :shortcode: patterns to Unicode emoji characters.
 * Unknown shortcodes (custom workspace emoji) are left as-is.
 */

const SKIN_TONE_MODIFIERS: Record<string, string> = {
  '2': '\u{1F3FB}',
  '3': '\u{1F3FC}',
  '4': '\u{1F3FD}',
  '5': '\u{1F3FE}',
  '6': '\u{1F3FF}',
};

const SKIN_TONE_ELIGIBLE = new Set<string>([
  'thumbsup',
  'thumbsdown',
  '+1',
  '-1',
  'wave',
  'raised_hand',
  'clap',
  'pray',
  'point_up',
  'point_down',
  'point_left',
  'point_right',
  'ok_hand',
  'muscle',
  'v',
  'raised_hands',
  'writing_hand',
  'hand',
  'open_hands',
  'palms_up_together',
  'punch',
  'fist',
  'left_facing_fist',
  'right_facing_fist',
  'crossed_fingers',
  'love_you_gesture',
  'metal',
  'call_me_hand',
  'vulcan_salute',
  'pinching_hand',
  'pinched_fingers',
  'index_pointing_up',
  'raised_back_of_hand',
  'middle_finger',
]);

const SLACK_EMOJI_MAP: Record<string, string> = {
  // Smileys & Faces
  smile: '😄',
  laughing: '😆',
  satisfied: '😆',
  blush: '😊',
  smiley: '😃',
  relaxed: '☺️',
  grinning: '😀',
  grin: '😁',
  joy: '😂',
  rofl: '🤣',
  rolling_on_the_floor_laughing: '🤣',
  sweat_smile: '😅',
  innocent: '😇',
  wink: '😉',
  heart_eyes: '😍',
  smiling_face_with_3_hearts: '🥰',
  star_struck: '🤩',
  kissing_heart: '😘',
  kissing: '😗',
  kissing_smiling_eyes: '😙',
  kissing_closed_eyes: '😚',
  yum: '😋',
  stuck_out_tongue: '😛',
  stuck_out_tongue_winking_eye: '😜',
  zany_face: '🤪',
  stuck_out_tongue_closed_eyes: '😝',
  money_mouth_face: '🤑',
  hugging_face: '🤗',
  hugs: '🤗',
  nerd_face: '🤓',
  sunglasses: '😎',
  disguised_face: '🥸',
  cowboy_hat_face: '🤠',
  partying_face: '🥳',
  smirk: '😏',
  unamused: '😒',
  disappointed: '😞',
  pensive: '😔',
  worried: '😟',
  confused: '😕',
  slightly_frowning_face: '🙁',
  frowning_face: '☹️',
  persevere: '😣',
  confounded: '😖',
  tired_face: '😫',
  weary: '😩',
  pleading_face: '🥺',
  cry: '😢',
  sob: '😭',
  triumph: '😤',
  rage: '😡',
  angry: '😠',
  face_with_symbols_on_mouth: '🤬',
  exploding_head: '🤯',
  flushed: '😳',
  hot_face: '🥵',
  cold_face: '🥶',
  scream: '😱',
  fearful: '😨',
  cold_sweat: '😰',
  disappointed_relieved: '😥',
  sweat: '😓',
  thinking_face: '🤔',
  thinking: '🤔',
  shushing_face: '🤫',
  hand_over_mouth: '🤭',
  saluting_face: '🫡',
  zipper_mouth_face: '🤐',
  face_with_raised_eyebrow: '🤨',
  neutral_face: '😐',
  expressionless: '😑',
  no_mouth: '😶',
  face_in_clouds: '😶‍🌫️',
  dotted_line_face: '🫥',
  smiling_face_with_tear: '🥲',
  face_exhaling: '😮‍💨',
  slightly_smiling_face: '🙂',
  upside_down_face: '🙃',
  face_with_rolling_eyes: '🙄',
  grimacing: '😬',
  face_with_peeking_eye: '🫣',
  lying_face: '🤥',
  shaking_face: '🫨',
  relieved: '😌',
  sleepy: '😪',
  drooling_face: '🤤',
  sleeping: '😴',
  mask: '😷',
  face_with_thermometer: '🤒',
  face_with_head_bandage: '🤕',
  nauseated_face: '🤢',
  face_vomiting: '🤮',
  sneezing_face: '🤧',
  woozy_face: '🥴',
  dizzy_face: '😵',
  face_with_spiral_eyes: '😵‍💫',
  ghost: '👻',
  skull: '💀',
  skull_and_crossbones: '☠️',
  alien: '👽',
  robot_face: '🤖',
  robot: '🤖',
  jack_o_lantern: '🎃',
  clown_face: '🤡',
  poop: '💩',
  hankey: '💩',
  see_no_evil: '🙈',
  hear_no_evil: '🙉',
  speak_no_evil: '🙊',
  imp: '👿',
  smiling_imp: '😈',

  // Hand Gestures
  '+1': '👍',
  thumbsup: '👍',
  '-1': '👎',
  thumbsdown: '👎',
  wave: '👋',
  raised_hand: '✋',
  hand: '✋',
  ok_hand: '👌',
  pinching_hand: '🤏',
  pinched_fingers: '🤌',
  v: '✌️',
  crossed_fingers: '🤞',
  love_you_gesture: '🤟',
  metal: '🤘',
  call_me_hand: '🤙',
  point_left: '👈',
  point_right: '👉',
  point_up_2: '👆',
  point_up: '☝️',
  point_down: '👇',
  middle_finger: '🖕',
  raised_back_of_hand: '🤚',
  open_hands: '👐',
  palms_up_together: '🤲',
  clap: '👏',
  raised_hands: '🙌',
  pray: '🙏',
  handshake: '🤝',
  writing_hand: '✍️',
  muscle: '💪',
  punch: '👊',
  fist: '✊',
  left_facing_fist: '🤛',
  right_facing_fist: '🤜',
  vulcan_salute: '🖖',
  index_pointing_up: '☝️',

  // Hearts & Symbols
  heart: '❤️',
  red_heart: '❤️',
  orange_heart: '🧡',
  yellow_heart: '💛',
  green_heart: '💚',
  blue_heart: '💙',
  purple_heart: '💜',
  black_heart: '🖤',
  white_heart: '🤍',
  brown_heart: '🤎',
  pink_heart: '🩷',
  broken_heart: '💔',
  heartpulse: '💗',
  heartbeat: '💓',
  two_hearts: '💕',
  revolving_hearts: '💞',
  sparkling_heart: '💖',
  cupid: '💘',
  gift_heart: '💝',
  heart_decoration: '💟',
  heavy_heart_exclamation_mark_ornament: '❣️',
  heart_on_fire: '❤️‍🔥',
  mending_heart: '❤️‍🩹',
  star: '⭐',
  star2: '🌟',
  sparkles: '✨',
  dizzy: '💫',
  boom: '💥',
  collision: '💥',
  fire: '🔥',
  flame: '🔥',
  zap: '⚡',
  '100': '💯',
  exclamation: '❗',
  question: '❓',
  grey_exclamation: '❕',
  grey_question: '❔',
  bangbang: '‼️',
  interrobang: '⁉️',
  x: '❌',
  o: '⭕',
  stop_sign: '🛑',
  no_entry: '⛔',
  warning: '⚠️',
  radioactive_sign: '☢️',
  biohazard_sign: '☣️',

  // Common Objects
  eyes: '👀',
  eye: '👁️',
  brain: '🧠',
  mega: '📣',
  loudspeaker: '📢',
  bell: '🔔',
  no_bell: '🔕',
  speech_balloon: '💬',
  thought_balloon: '💭',
  bulb: '💡',
  mag: '🔍',
  mag_right: '🔎',
  lock: '🔒',
  unlock: '🔓',
  key: '🔑',
  gear: '⚙️',
  wrench: '🔧',
  hammer: '🔨',
  nut_and_bolt: '🔩',
  link: '🔗',
  chains: '⛓️',
  scissors: '✂️',
  paperclip: '📎',
  pushpin: '📌',
  round_pushpin: '📍',
  triangular_flag_on_post: '🚩',
  flag_white: '🏳️',
  flag_black: '🏴',
  bookmark: '🔖',
  label: '🏷️',
  moneybag: '💰',
  money_with_wings: '💸',
  credit_card: '💳',
  envelope: '✉️',
  email: '📧',
  'e-mail': '📧',
  inbox_tray: '📥',
  outbox_tray: '📤',
  package: '📦',
  memo: '📝',
  pencil: '📝',
  pencil2: '✏️',
  pen_ballpoint: '🖊️',
  pen_fountain: '🖋️',
  clipboard: '📋',
  file_folder: '📁',
  open_file_folder: '📂',
  page_facing_up: '📄',
  page_with_curl: '📃',
  newspaper: '📰',
  notebook: '📓',
  notebook_with_decorative_cover: '📔',
  books: '📚',
  book: '📖',
  open_book: '📖',
  calendar: '📅',
  date: '📅',
  spiral_calendar_pad: '🗓️',
  chart_with_upwards_trend: '📈',
  chart_with_downwards_trend: '📉',
  bar_chart: '📊',
  clock1: '🕐',
  clock2: '🕑',
  clock3: '🕒',
  clock4: '🕓',
  clock5: '🕔',
  clock6: '🕕',
  clock7: '🕖',
  clock8: '🕗',
  clock9: '🕘',
  clock10: '🕙',
  clock11: '🕚',
  clock12: '🕛',
  hourglass: '⌛',
  hourglass_flowing_sand: '⏳',
  stopwatch: '⏱️',
  alarm_clock: '⏰',
  timer_clock: '⏲️',
  phone: '📱',
  iphone: '📱',
  telephone: '☎️',
  telephone_receiver: '📞',
  computer: '💻',
  desktop_computer: '🖥️',
  keyboard: '⌨️',
  printer: '🖨️',
  mouse_three_button: '🖱️',
  floppy_disk: '💾',
  cd: '💿',
  dvd: '📀',
  tv: '📺',
  camera: '📷',
  video_camera: '📹',
  movie_camera: '🎥',
  microphone: '🎤',
  headphones: '🎧',
  battery: '🔋',
  electric_plug: '🔌',

  // Celebrations & Activities
  tada: '🎉',
  confetti_ball: '🎊',
  balloon: '🎈',
  birthday: '🎂',
  gift: '🎁',
  trophy: '🏆',
  medal: '🏅',
  first_place_medal: '🥇',
  second_place_medal: '🥈',
  third_place_medal: '🥉',
  ribbon: '🎀',
  rosette: '🏵️',
  crystal_ball: '🔮',
  dart: '🎯',
  bowling: '🎳',
  video_game: '🎮',
  joystick: '🕹️',
  game_die: '🎲',
  jigsaw: '🧩',
  art: '🎨',

  // Food & Drink
  coffee: '☕',
  tea: '🍵',
  beer: '🍺',
  beers: '🍻',
  clinking_glasses: '🥂',
  wine_glass: '🍷',
  cocktail: '🍸',
  tropical_drink: '🍹',
  sake: '🍶',
  pizza: '🍕',
  hamburger: '🍔',
  fries: '🍟',
  hotdog: '🌭',
  taco: '🌮',
  burrito: '🌯',
  sushi: '🍣',
  ramen: '🍜',
  rice: '🍚',
  rice_ball: '🍙',
  curry: '🍛',
  bento: '🍱',
  egg: '🥚',
  cooking: '🍳',
  cake: '🍰',
  cookie: '🍪',
  doughnut: '🍩',
  chocolate_bar: '🍫',
  ice_cream: '🍨',
  icecream: '🍦',
  lollipop: '🍭',
  apple: '🍎',
  green_apple: '🍏',
  banana: '🍌',
  grapes: '🍇',
  watermelon: '🍉',
  strawberry: '🍓',
  peach: '🍑',
  cherries: '🍒',
  lemon: '🍋',
  tangerine: '🍊',
  avocado: '🥑',
  broccoli: '🥦',
  carrot: '🥕',
  corn: '🌽',
  hot_pepper: '🌶️',

  // Nature & Weather
  sunny: '☀️',
  sun_with_face: '🌞',
  cloud: '☁️',
  partly_sunny: '⛅',
  umbrella: '☂️',
  snowflake: '❄️',
  snowman: '⛄',
  rainbow: '🌈',
  ocean: '🌊',
  wind_blowing_face: '🌬️',
  cyclone: '🌀',
  earth_americas: '🌎',
  earth_africa: '🌍',
  earth_asia: '🌏',
  globe_with_meridians: '🌐',
  full_moon: '🌕',
  crescent_moon: '🌙',
  new_moon_with_face: '🌚',
  seedling: '🌱',
  evergreen_tree: '🌲',
  deciduous_tree: '🌳',
  palm_tree: '🌴',
  cactus: '🌵',
  herb: '🌿',
  shamrock: '☘️',
  four_leaf_clover: '🍀',
  fallen_leaf: '🍂',
  maple_leaf: '🍁',
  leaves: '🍃',
  mushroom: '🍄',
  tulip: '🌷',
  sunflower: '🌻',
  rose: '🌹',
  cherry_blossom: '🌸',
  bouquet: '💐',
  hibiscus: '🌺',
  blossom: '🌼',

  // Animals
  dog: '🐶',
  cat: '🐱',
  mouse_face: '🐭',
  hamster: '🐹',
  rabbit: '🐰',
  bear: '🐻',
  panda_face: '🐼',
  koala: '🐨',
  tiger: '🐯',
  lion_face: '🦁',
  lion: '🦁',
  cow: '🐮',
  pig: '🐷',
  frog: '🐸',
  monkey_face: '🐵',
  chicken: '🐔',
  penguin: '🐧',
  bird: '🐦',
  eagle: '🦅',
  owl: '🦉',
  bat: '🦇',
  wolf: '🐺',
  fox_face: '🦊',
  raccoon: '🦝',
  unicorn_face: '🦄',
  unicorn: '🦄',
  bee: '🐝',
  honeybee: '🐝',
  bug: '🐛',
  butterfly: '🦋',
  snail: '🐌',
  lady_beetle: '🐞',
  ladybug: '🐞',
  ant: '🐜',
  spider: '🕷️',
  spider_web: '🕸️',
  turtle: '🐢',
  snake: '🐍',
  octopus: '🐙',
  whale: '🐳',
  dolphin: '🐬',
  fish: '🐟',
  tropical_fish: '🐠',
  blowfish: '🐡',
  shark: '🦈',
  crab: '🦀',
  shrimp: '🦐',
  squid: '🦑',

  // Travel & Transport
  rocket: '🚀',
  airplane: '✈️',
  helicopter: '🚁',
  car: '🚗',
  red_car: '🚗',
  taxi: '🚕',
  bus: '🚌',
  ambulance: '🚑',
  fire_engine: '🚒',
  police_car: '🚓',
  truck: '🚚',
  bike: '🚲',
  scooter: '🛴',
  motorcycle: '🏍️',
  train: '🚆',
  metro: '🚇',
  ship: '🚢',
  sailboat: '⛵',
  anchor: '⚓',
  construction: '🚧',
  fuelpump: '⛽',
  world_map: '🗺️',
  compass: '🧭',
  mountain: '⛰️',
  mount_fuji: '🗻',
  house: '🏠',
  office: '🏢',
  hospital: '🏥',
  school: '🏫',
  church: '⛪',
  tent: '⛺',
  tokyo_tower: '🗼',
  statue_of_liberty: '🗽',

  // Checkmarks & UI
  white_check_mark: '✅',
  heavy_check_mark: '✔️',
  ballot_box_with_check: '☑️',
  heavy_plus_sign: '➕',
  heavy_minus_sign: '➖',
  heavy_multiplication_x: '✖️',
  heavy_division_sign: '➗',
  arrow_right: '➡️',
  arrow_left: '⬅️',
  arrow_up: '⬆️',
  arrow_down: '⬇️',
  arrow_upper_right: '↗️',
  arrow_lower_right: '↘️',
  arrow_upper_left: '↖️',
  arrow_lower_left: '↙️',
  left_right_arrow: '↔️',
  arrow_up_down: '↕️',
  arrows_counterclockwise: '🔄',
  arrows_clockwise: '🔃',
  back: '🔙',
  end: '🔚',
  on: '🔛',
  soon: '🔜',
  top: '🔝',
  new: '🆕',
  free: '🆓',
  up: '🆙',
  cool: '🆒',
  ok: '🆗',
  sos: '🆘',
  no_entry_sign: '🚫',
  underage: '🔞',
  recycle: '♻️',
  white_circle: '⚪',
  black_circle: '⚫',
  red_circle: '🔴',
  large_blue_circle: '🔵',
  large_orange_circle: '🟠',
  large_yellow_circle: '🟡',
  large_green_circle: '🟢',
  large_purple_circle: '🟣',
  large_brown_circle: '🟤',
  black_square: '⬛',
  white_square: '⬜',
  large_blue_diamond: '🔷',
  large_orange_diamond: '🔶',
  small_blue_diamond: '🔹',
  small_orange_diamond: '🔸',
  small_red_triangle: '🔺',
  small_red_triangle_down: '🔻',
  diamond_shape_with_a_dot_inside: '💠',
  radio_button: '🔘',
  black_small_square: '▪️',
  white_small_square: '▫️',
  black_medium_square: '◼️',
  white_medium_square: '◻️',
  black_medium_small_square: '◾',
  white_medium_small_square: '◽',
  black_large_square: '⬛',
  white_large_square: '⬜',

  // People & Roles
  raising_hand: '🙋',
  person_bowing: '🙇',
  bow: '🙇',
  person_facepalming: '🤦',
  facepalm: '🤦',
  person_shrugging: '🤷',
  shrug: '🤷',
  person_raising_hand: '🙋',
  no_good: '🙅',
  ok_woman: '🙆',
  information_desk_person: '💁',
  sassy: '💁',
  tipping_hand_person: '💁',
  dancer: '💃',
  man_dancing: '🕺',
  running: '🏃',
  walking: '🚶',
  standing_person: '🧍',
  kneeling_person: '🧎',
  technologist: '🧑‍💻',
  adult: '🧑',
  child: '🧒',
  baby: '👶',
  man: '👨',
  woman: '👩',
  older_man: '👴',
  older_woman: '👵',
  couple_with_heart: '💑',
  kiss: '💋',
  family: '👪',
  people_holding_hands: '🧑‍🤝‍🧑',
  busts_in_silhouette: '👥',
  bust_in_silhouette: '👤',
  footprints: '👣',

  // Misc common
  zzz: '💤',
  wave_dash: '〰️',
  musical_note: '🎵',
  notes: '🎶',
  microphone2: '🎙️',
  headstone: '🪦',
  infinity: '♾️',
  peace_symbol: '☮️',
  yin_yang: '☯️',
  beginner: '🔰',
  trident: '🔱',
  'fleur-de-lis': '⚜️',
  atom_symbol: '⚛️',
  wheel_of_dharma: '☸️',
  sparkle: '❇️',
  eight_spoked_asterisk: '✳️',
  eight_pointed_black_star: '✴️',
  cross_mark: '❌',
  negative_squared_cross_mark: '❎',
  curly_loop: '➰',
  loop: '➿',
  hash: '#️⃣',
  keycap_star: '*️⃣',
  zero: '0️⃣',
  one: '1️⃣',
  two: '2️⃣',
  three: '3️⃣',
  four: '4️⃣',
  five: '5️⃣',
  six: '6️⃣',
  seven: '7️⃣',
  eight: '8️⃣',
  nine: '9️⃣',
  keycap_ten: '🔟',
  a: '🅰️',
  b: '🅱️',
  ab: '🆎',
  cl: '🆑',
  information_source: 'ℹ️',
  abc: '🔤',
  abcd: '🔡',
  capital_abcd: '🔠',
  symbols: '🔣',
  wavy_dash: '〰️',
  copyright: '©️',
  registered: '®️',
  tm: '™️',

  // Flags (common)
  jp: '🇯🇵',
  'flag-jp': '🇯🇵',
  us: '🇺🇸',
  'flag-us': '🇺🇸',
  gb: '🇬🇧',
  'flag-gb': '🇬🇧',
  uk: '🇬🇧',
  cn: '🇨🇳',
  'flag-cn': '🇨🇳',
  kr: '🇰🇷',
  'flag-kr': '🇰🇷',
  de: '🇩🇪',
  'flag-de': '🇩🇪',
  fr: '🇫🇷',
  'flag-fr': '🇫🇷',
  es: '🇪🇸',
  'flag-es': '🇪🇸',
  it: '🇮🇹',
  'flag-it': '🇮🇹',
  ru: '🇷🇺',
  'flag-ru': '🇷🇺',
  au: '🇦🇺',
  'flag-au': '🇦🇺',
  ca: '🇨🇦',
  'flag-ca': '🇨🇦',
  br: '🇧🇷',
  'flag-br': '🇧🇷',
  in: '🇮🇳',
  'flag-in': '🇮🇳',
  checkered_flag: '🏁',
  rainbow_flag: '🏳️‍🌈',
  pirate_flag: '🏴‍☠️',
  triangular_flag: '🚩',

  // Sports
  soccer: '⚽',
  basketball: '🏀',
  football: '🏈',
  baseball: '⚾',
  tennis: '🎾',
  volleyball: '🏐',
  golf: '⛳',
  ping_pong: '🏓',
  badminton: '🏸',
  ice_hockey: '🏒',
  ski: '🎿',
  swimmer: '🏊',
  surfing_man: '🏄',
  weight_lifter: '🏋️',
  wrestling: '🤼',
  boxing_glove: '🥊',
  martial_arts_uniform: '🥋',
  horse_racing: '🏇',
};

const SLACK_EMOJI_REGEX = /(?<![a-zA-Z0-9:\/]):([\w+\-]+):(?::skin-tone-(\d):)?/g;

export function convertSlackEmoji(text: string): string {
  return text.replace(SLACK_EMOJI_REGEX, (match, shortcode: string, skinTone?: string) => {
    const emoji = SLACK_EMOJI_MAP[shortcode];
    if (!emoji) {
      return match;
    }
    if (skinTone && SKIN_TONE_MODIFIERS[skinTone] && SKIN_TONE_ELIGIBLE.has(shortcode)) {
      return emoji + SKIN_TONE_MODIFIERS[skinTone];
    }
    return emoji;
  });
}
